spring:

  shell:
    interactive:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    password: 1
    username: postgres
    url: jdbc:postgresql://localhost:5432/mydb

  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
