logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.cloud.gateway: DEBUG  # вк

spring:
  application:
    name: api-gateway


server:
  port: 7777

# пользователи
# http://localhost:8080/api/user/456
#
# токен
# http://localhost:8080/api/token
#
# игры
# http://localhost:8082/api/game/1/2

application:
  api-routes:
    - id: "service-user"
      from: "api/user"
      to: "lb://USER"
#      to: "http://localhost:8087"
    - id: "service-game"
      from: "api/game"
      to: "lb://FRONT-GAME"
#      to: "lb://GAME"
#      to: "http://localhost:8089"
    - id: "service-token"
      from: "api/token"
      to: "lb://SEQURITY"
#      to: "http://localhost:8085"

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      zone: zone1
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - metrics
          - refresh
    enabled-by-default: false