DROP TABLE if EXISTS public.repayment CASCADE;

CREATE TABLE repayment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   num_cred VARCHAR,
   status VARCHAR,
   json_data jsonb,
   CONSTRAINT pk_repayment PRIMARY KEY (id)
);