services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres:5432/db
      - SPRING_FLYWAY_USERNAME=postgres
      - SPRING_FLYWAY_PASSWORD=postgres
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/db
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=postgres
    networks:
        - bdnet

  postgres:
    image: "postgres"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    networks:
          - bdnet

networks:
  bdnet:
    driver: bridge
