logging:
  level:
    ru.otus.hw.ex06.*: DEBUG

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:mem:testdb

  #  datasource:
#    driver-class-name: org.postgresql.Driver
#    password: 1
#    username: postgres
#    url: jdbc:postgresql://localhost/mydb

  shell:
    interactive:
      enabled: true


  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
      #format_sql: true
