spring:

  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:mem:hw

  shell:
    interactive:
      enabled: true


  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
      #format_sql: true
