logging:
  level:
    ru.otus.hw.ex00.*: DEBUG
    org.hibernate.SQL: DEBUG

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    password: 1
    username: postgres
    url: jdbc:postgresql://localhost/mydb

  #  datasource:
  #    driver-class-name: org.h2.Driver
  #    password: ''
  #    username: sa
  #    url: jdbc:h2:mem:hw


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql
