version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - 8081:8081
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5433/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - WAIT_FOR=db:5432
    networks:
      - nw
  db:
    image: "postgres"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    networks:
      - nw
networks:
  nw:
