spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 1
    username: postgres
    url: jdbc:postgresql://localhost/mydb
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql
